#!/bin/sh

### BEGIN INIT INFO
# Provides:start_uvc_gadget
# Required-Start:$remote_fs $syslog
# Required-Stop:$remote_fs $syslog
# Default-Start:2 3 4 5
# Default-Stop:0 1 6
# Short-Description: start_uvc_gadget
# Description: This service is used to  start_uvc_gadget 
### END INIT INFO


#!/bin/bash
case "$1" in
    start):
        echo "Starting UVC Gadget "
        sudo /home/pi/vio/raspberry_zero_vio/usb_gadget/start_uvc_gadget.sh &
    ;;
    stop):
        echo "to"
        echo "Usage: service start_uvc_gadget start|stop"
        exit 1 ;;
esac

exit 0

